name: cawaf_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  equatable: ^2.0.3
  easy_localization: ^3.0.0
  cawaf_services_api:
    git:
      url: git@github.com:WillCafDev/cawaf_services_api.git
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  reactive_forms: ^10.6.8
  rive: ^0.7.33
  provider: ^6.0.1
  logger: ^1.0.0
  freezed: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1
  freezed_annotation: ^1.1.0
  internet_connection_checker: ^0.0.1+3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logos/
    - assets/translations/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: 'Montserrat'
      fonts:
        - asset: 'assets/fonts/Montserrat-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/Montserrat-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/Montserrat-SemiBold.ttf'
          weight: 600
        - asset: 'assets/fonts/Montserrat-Bold.ttf'
          weight: 700

